language: objective-c

osx_image: xcode8

before_install:
  - make bootstrap

script:
  - make build-pretty test-pretty lint carthage

before_deploy:
  - make archive

deploy:
  provider: releases
  api_key:
    secure: Y/9IQgi3FaZv4Ev/TmJWR1kWsW6fy5r0I6XtiC9z++wuw+y1C1iiaMIdXHA1YP9oOuSCUv3vpRdak5CltumRR++65ufNq6y3LdsywNPVGBkaSYJLmf4eBIDMBZvy3qFoGjBKyQunErAQwIsnFsk6VZ1KM6vRWqjwXkcqLGuJoUE=
  file: Analytics.framework.zip
  skip_cleanup: true
  on:
    repo: segmentio/analytics-ios
    tags: true

notifications:
  email: false
